# Site settings
title: Barbados
client:
  name: Destination Barbados
  link: https://www.visitbarbados.org/
core-se-link: https://www.secretescapes.com/current-sales
description: >
  This sun-drenched Caribbean starlet is the perfect place to indulge mind, body and soul – the beach is calling.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/barbados" # the subpath of your site, e.g. /blog/
img:     "/barbados/_assets/img"
css:     "/barbados/_assets/css"
js:      "/barbados/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed